vim.keymap.set("n", "<leader>e", ":Neotree toggle<CR>")
vim.keymap.set("n", "<leader>ff", ":Telescope find_files<CR>")
vim.keymap.set("n", "<leader>fg", ":Telescope live_grep<CR>")
vim.keymap.set("n", "<leader>fr", ":Telescope oldfiles<CR>")
vim.keymap.set("n", "<leader>e", ":Neotree toggle<CR>")
vim.keymap.set("n", "<leader>th", ":Telescope colorscheme<CR>")
vim.keymap.set("n", "<leader>ft", vim.lsp.buf.format, {})
vim.keymap.set("n", "<C-/>", ":CommentToggle<CR>")
vim.keymap.set("n", "L", ":BufferNext<CR>")
vim.keymap.set("n", "H", ":BufferPrevious<CR>")
vim.keymap.set("n", "<leader>bx", ":BufferClose<CR>")
vim.keymap.set("n", "<leader>br", ":BufferRestore<CR>")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("n", "<leader>cl", ":VimtexCompile<CR>")
vim.keymap.set('n', 'd', '"_d')
vim.keymap.set('v', 'd', '"_d')
